//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.Interviewers = new HashSet<Interviewer>();
            this.Recruiters = new HashSet<Recruiter>();
            this.Resources = new HashSet<Resource>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> NoofLogins { get; set; }
        public Nullable<int> NoofAttempts { get; set; }
        public string PhoneNo { get; set; }
    
        public virtual ICollection<Interviewer> Interviewers { get; set; }
        public virtual ICollection<Recruiter> Recruiters { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
    }
}
