//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientDocuments = new HashSet<ClientDocument>();
            this.Interviews = new HashSet<Interview>();
            this.Requirements = new HashSet<Requirement>();
            this.Requirements1 = new HashSet<Requirement>();
            this.Resources = new HashSet<Resource>();
        }
    
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string BillingContact { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public bool BlackListed { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<ClientDocument> ClientDocuments { get; set; }
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual ICollection<Requirement> Requirements { get; set; }
        public virtual ICollection<Requirement> Requirements1 { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
    }
}
