//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionType
    {
        public CommissionType()
        {
            this.RecruiterTargets = new HashSet<RecruiterTarget>();
        }
    
        public int CommissionTypeId { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public bool IsPercentage { get; set; }
    
        public virtual ICollection<RecruiterTarget> RecruiterTargets { get; set; }
    }
}
