//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.ClientDocuments = new HashSet<ClientDocument>();
            this.InterviewDocuments = new HashSet<InterviewDocument>();
            this.ResourceDocuments = new HashSet<ResourceDocument>();
            this.VendorDocuments = new HashSet<VendorDocument>();
        }
    
        public int DocumentTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> DocumentGroup { get; set; }
    
        public virtual ICollection<ClientDocument> ClientDocuments { get; set; }
        public virtual ICollection<InterviewDocument> InterviewDocuments { get; set; }
        public virtual ICollection<ResourceDocument> ResourceDocuments { get; set; }
        public virtual ICollection<VendorDocument> VendorDocuments { get; set; }
    }
}
