//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public Interview()
        {
            this.InterviewDetails = new HashSet<InterviewDetail>();
            this.InterviewDocuments = new HashSet<InterviewDocument>();
        }
    
        public int InterviewId { get; set; }
        public int ResourceId { get; set; }
        public string PhoneNo { get; set; }
        public string MeetingLink { get; set; }
        public string Feedback { get; set; }
        public string Status { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> InterviewerId { get; set; }
        public bool FeePaid { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> RequirementId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public int InterviewType { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Interviewer Interviewer { get; set; }
        public virtual Requirement Requirement { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ICollection<InterviewDetail> InterviewDetails { get; set; }
        public virtual ICollection<InterviewDocument> InterviewDocuments { get; set; }
    }
}
