//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public int ResourceId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime WeekOf { get; set; }
        public decimal Amount { get; set; }
        public string FilePath { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
