//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public ProjectDetail()
        {
            this.Timesheets = new HashSet<Timesheet>();
        }
    
        public int ProjectDetailId { get; set; }
        public int RequirementId { get; set; }
        public int ResourceId { get; set; }
        public int RecruiterId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime PlacementDate { get; set; }
        public Nullable<int> AccountManagerId { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
        public virtual Requirement Requirement { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
