//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruiterTarget
    {
        public int RecruiterTargetId { get; set; }
        public int RecruiterId { get; set; }
        public int Year { get; set; }
        public System.DateTime TargetDate { get; set; }
        public int TargetType { get; set; }
        public int TargetCount { get; set; }
        public bool TargetReached { get; set; }
        public Nullable<int> NoofResumesContributed { get; set; }
        public Nullable<decimal> CommissionAccrued { get; set; }
        public Nullable<decimal> CommissionPaid { get; set; }
        public Nullable<int> H1BContributed { get; set; }
        public Nullable<int> W2Placement { get; set; }
        public Nullable<int> CTCPlacement { get; set; }
        public Nullable<int> C1099Placement { get; set; }
        public Nullable<int> CitizenPlacement { get; set; }
        public Nullable<int> CTHPlacement { get; set; }
        public Nullable<int> ProActiveHiring { get; set; }
        public Nullable<decimal> Profitability { get; set; }
        public int CommissionTypeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
    
        public virtual CommissionType CommissionType { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
