//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruiter
    {
        public Recruiter()
        {
            this.RecruiterTargets = new HashSet<RecruiterTarget>();
            this.RequirementDetails = new HashSet<RequirementDetail>();
            this.ProjectDetails = new HashSet<ProjectDetail>();
        }
    
        public int RecruiterId { get; set; }
        public string Specialty { get; set; }
        public string AreasOfImprovment { get; set; }
        public string CareerPath { get; set; }
        public string Communities { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string UserId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
    
        public virtual ICollection<RecruiterTarget> RecruiterTargets { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<RequirementDetail> RequirementDetails { get; set; }
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
    }
}
