//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public Requirement()
        {
            this.Interviews = new HashSet<Interview>();
            this.RequirementDetails = new HashSet<RequirementDetail>();
            this.RequirementSkillSets = new HashSet<RequirementSkillSet>();
            this.ProjectDetails = new HashSet<ProjectDetail>();
        }
    
        public int RequirementId { get; set; }
        public string JobNumber { get; set; }
        public int Priority { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> HourlyBuyRate { get; set; }
        public Nullable<decimal> HourlyBillingRate { get; set; }
        public int JobTypeId { get; set; }
        public Nullable<decimal> OneTimeFee { get; set; }
        public Nullable<int> InternalResumeCount { get; set; }
        public Nullable<int> ClientResumeCount { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReasonNotClosed { get; set; }
        public Nullable<int> RecruiterId { get; set; }
        public Nullable<int> Tier1ClientId { get; set; }
        public Nullable<int> Tier2ClientId { get; set; }
        public Nullable<int> AccountManagerId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public string Duration { get; set; }
        public string JobTitle { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual ICollection<RequirementDetail> RequirementDetails { get; set; }
        public virtual ICollection<RequirementSkillSet> RequirementSkillSets { get; set; }
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
    }
}
