//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementDetail
    {
        public int RequirementDetailId { get; set; }
        public int RequirementId { get; set; }
        public int RecruiterId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public bool ReferredToClient { get; set; }
        public bool CandidateSelected { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
    
        public virtual Requirement Requirement { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
