//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.Interviews = new HashSet<Interview>();
            this.Interviewers = new HashSet<Interviewer>();
            this.Invoices = new HashSet<Invoice>();
            this.RequirementDetails = new HashSet<RequirementDetail>();
            this.ResourceDocuments = new HashSet<ResourceDocument>();
            this.ResourceSkillSets = new HashSet<ResourceSkillSet>();
            this.Timesheets = new HashSet<Timesheet>();
            this.ProjectDetails = new HashSet<ProjectDetail>();
        }
    
        public int ResourceId { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int ResourceTypeId { get; set; }
        public string PhoneNo2 { get; set; }
        public string Email2 { get; set; }
        public string LinkedInProfile { get; set; }
        public string SkypeId { get; set; }
        public Nullable<decimal> YearsOfExperience { get; set; }
        public bool PersonalInterview { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> CTC { get; set; }
        public bool SwitchLaneInterviewed { get; set; }
        public Nullable<int> NoofClientInterviews { get; set; }
        public string DomainExpertise { get; set; }
        public string LocationPreference { get; set; }
        public bool BackgroundCheck { get; set; }
        public bool EducationCertificates { get; set; }
        public bool VisaCopy { get; set; }
        public bool PassPortCopy { get; set; }
        public bool LicenseCopy { get; set; }
        public bool PhotoId { get; set; }
        public bool I9Form { get; set; }
        public bool GreenCardDocuments { get; set; }
        public bool PayStubs { get; set; }
        public bool W2Copy { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> NoofKids { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public Nullable<System.DateTime> LastMeetingDate { get; set; }
        public Nullable<System.DateTime> NextMeetingDate { get; set; }
        public string TrainingAreas { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public Nullable<System.DateTime> SpouseDOB { get; set; }
        public Nullable<System.DateTime> Kid1DOB { get; set; }
        public Nullable<System.DateTime> Kid2DOB { get; set; }
        public Nullable<int> ReferrerId { get; set; }
        public Nullable<decimal> ReferralAmountDue { get; set; }
        public Nullable<int> ReferredConsultantId { get; set; }
        public Nullable<int> Tier1VendorId { get; set; }
        public Nullable<int> Tier2VendorId { get; set; }
        public Nullable<double> USExperience { get; set; }
        public Nullable<System.DateTime> VisaExpirationDate { get; set; }
        public bool EAD { get; set; }
        public bool OPT { get; set; }
        public Nullable<int> SSN { get; set; }
        public bool NDA { get; set; }
        public string Source { get; set; }
        public string Availability { get; set; }
        public bool BlackListed { get; set; }
        public string Notes { get; set; }
        public string Qualification { get; set; }
        public string ResidentialStatus { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UserId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string VisaType { get; set; }
        public string Ref1CompanyName { get; set; }
        public string Ref1Name { get; set; }
        public string Ref1Email { get; set; }
        public string Ref1Phone { get; set; }
        public string Ref1Designation { get; set; }
        public string Ref2CompanyName { get; set; }
        public string Ref2Name { get; set; }
        public string Ref2Email { get; set; }
        public string Ref2Phone { get; set; }
        public string Ref2Designation { get; set; }
        public string Ref3CompanyName { get; set; }
        public string Ref3Name { get; set; }
        public string Ref3Email { get; set; }
        public string Ref3Phone { get; set; }
        public string Ref3Designation { get; set; }
        public bool Medical { get; set; }
        public bool Vision { get; set; }
        public bool Dental { get; set; }
        public bool Relocation { get; set; }
        public bool FourZeroOneK { get; set; }
        public bool STD { get; set; }
        public bool LTD { get; set; }
        public bool LifeInsurance { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual ICollection<Interviewer> Interviewers { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Referrer Referrer { get; set; }
        public virtual ICollection<RequirementDetail> RequirementDetails { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual Vendor Vendor1 { get; set; }
        public virtual ICollection<ResourceDocument> ResourceDocuments { get; set; }
        public virtual ICollection<ResourceSkillSet> ResourceSkillSets { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
    }
}
