//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillSet
    {
        public SkillSet()
        {
            this.RequirementSkillSets = new HashSet<RequirementSkillSet>();
            this.ResourceSkillSets = new HashSet<ResourceSkillSet>();
            this.InterviewDetails = new HashSet<InterviewDetail>();
            this.InterviewerSkillSets = new HashSet<InterviewerSkillSet>();
        }
    
        public int SkillSetId { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<RequirementSkillSet> RequirementSkillSets { get; set; }
        public virtual ICollection<ResourceSkillSet> ResourceSkillSets { get; set; }
        public virtual ICollection<InterviewDetail> InterviewDetails { get; set; }
        public virtual ICollection<InterviewerSkillSet> InterviewerSkillSets { get; set; }
    }
}
