//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Resources = new HashSet<Resource>();
            this.Resources1 = new HashSet<Resource>();
            this.VendorDocuments = new HashSet<VendorDocument>();
        }
    
        public int VendorId { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNo { get; set; }
        public string BillingContact { get; set; }
        public string Terms { get; set; }
        public bool W9 { get; set; }
        public bool InsuranceCertificates { get; set; }
        public bool Contracts { get; set; }
        public bool BlackListed { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimestamp { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual ICollection<Resource> Resources1 { get; set; }
        public virtual ICollection<VendorDocument> VendorDocuments { get; set; }
    }
}
